//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::recipes::Entity as Recipes;
pub use super::transcript::Entity as Transcript;
pub use super::unprocessed_recipes::Entity as UnprocessedRecipes;
