//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::instagram_video::Entity as InstagramVideo;
pub use super::recipes::Entity as Recipes;
pub use super::transcript::Entity as Transcript;
